apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
spec:
  tls:
    - hosts:
        - example.com
      secretName: example-tls
  rules:
    - host: example.com
      http:
        paths:
          - path: /api/v1
            backend:
              serviceName: my-app-v1
              servicePort: http
          - path: /api/v2
            backend:
              serviceName: my-app-v2
              servicePort: http
