apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
namePrefix: test-
nameSuffix: -v2
commonLabels:
  app: myapp
  version: v2
commonAnnotations:
  repo-url: gitlab.com/mygroup/myapp
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: myapp-env
    env: settings.env
  - name: other-env
    literals:
      - NODE_ENV=production
secretGenerator:
  - name: myapp-env
    env: secrets.env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - service_port_8000.yaml
patchesJson6902:
  - target:
      version: networking.k8s.io/v1beta1
      kind: Ingress
      name: myapp
    path: patch-hostname.yaml
  # - op: replace
  #   path: /spec/rules/0/host
  #   value: new.example.com
vars:
  - name: SOME_SECRET_NAME
    objref:
      kind: Secret
      name: my-secret
      apiVersion: v1
  - name: MY_SERVICE_NAME
    objref:
      kind: Service
      name: my-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: ANOTHER_DEPLOYMENTS_POD_RESTART_POLICY
    objref:
      kind: Deployment
      name: my-deployment
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.restartPolicy
images:
  - name: appimage
    newName: gitlab.com/mygroup/myapp
    newTag: v2
