apiVersion: v1
kind: Service
metadata:
  name: my-app-v1
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: my-app-v1
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  type: ExternalName
  externalName: external.example.com
