apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: example
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "/usr/local/bin/redis-cli"
                  - "shutdown"
                  - "save"
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "/usr/local/bin/redis-cli"
                - "ping"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: db
            timeoutSeconds: 1
          ports:
            - containerPort: 6379
              name: db
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
        - name: exporter
          env:
            - name: REDIS_ADDR
              value: redis://localhost:6379
            - name: REDIS_EXPORTER_LOG_FORMAT
              value: json
          image: oliver006/redis_exporter:v1.1.0-alpine
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 9121
              name: db
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
    type: OnDelete
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
        volumeMode: Filesystem
